begin 
    dbms_output.put_line('Studend ID: 101953626');
    DELETE_ALL_CUSTOMERS_VIASQLDEV;
    DELETE_ALL_PRODUCTS_VIASQLDEV;
    dbms_output.put_line('================== TEST ADD CUSTOMERS ==================');
    ADD_CUSTOMER_VIASQLDEV(1, 'Colin Smith');
    ADD_CUSTOMER_VIASQLDEV(2, 'Jill Davids');
    ADD_CUSTOMER_VIASQLDEV(3, 'Dave Brown');
    ADD_CUSTOMER_VIASQLDEV(4, 'Kristy Glass');
    ADD_CUSTOMER_VIASQLDEV(1, 'Jenny Nighy');
    ADD_CUSTOMER_VIASQLDEV(-3, 'Emma Jones');
    ADD_CUSTOMER_VIASQLDEV(666, 'Peter While');
    dbms_output.put_line('================== TEST ADD PRODUCTS ==================');
    ADD_PRODUCT_VIASQLDEV(1001, 'ProdA', 10);
    ADD_PRODUCT_VIASQLDEV(1002, 'ProdB', 20);
    ADD_PRODUCT_VIASQLDEV(1003, 'ProdC', 35);
    ADD_PRODUCT_VIASQLDEV(1001, 'ProdD', 10);
    ADD_PRODUCT_VIASQLDEV(3333, 'ProdD', 100);
    ADD_PRODUCT_VIASQLDEV(1004, 'ProdD', 1234);
    dbms_output.put_line('================== TEST STATUS UPDATES ==================');
    UPD_CUST_STATUS_VIASQLDEV(3, 'SUSPEND');
    UPD_CUST_STATUS_VIASQLDEV(4, 'QWERTY');
    dbms_output.put_line('================== TEST CUSTOMER RETREIVAL ==================');
    GET_CUST_STRING_VIASQLDEV(1);
    GET_CUST_STRING_VIASQLDEV(2);
    GET_CUST_STRING_VIASQLDEV(22);
    dbms_output.put_line('================== TEST PRODUCT RETREIVAL ==================');
    GET_PROD_STRING_VIASQLDEV(1001);
    GET_PROD_STRING_VIASQLDEV(1002);
    GET_PROD_STRING_VIASQLDEV(2222);
    dbms_output.put_line('================== TEST SIMPLE SALES ==================');
    ADD_SIMPLE_SALE_VIASQLDEV(1, 1001, 15);
    ADD_SIMPLE_SALE_VIASQLDEV(2, 1002, 37);
    ADD_SIMPLE_SALE_VIASQLDEV(3, 1002, 15);
    ADD_SIMPLE_SALE_VIASQLDEV(4, 1001, 100);
    SUM_CUST_SALES_VIASQLDEV();
    SUM_PROD_SALES_VIASQLDEV();
    dbms_output.put_line('================== MORE TESTING OF SIMPLE SALES ==================');
    ADD_SIMPLE_SALE_VIASQLDEV(99, 1002, 60);
    ADD_SIMPLE_SALE_VIASQLDEV(3, 5555, 60);
    ADD_SIMPLE_SALE_VIASQLDEV(1, 1002, 6666);
    SUM_CUST_SALES_VIASQLDEV();
    SUM_PROD_SALES_VIASQLDEV();
    dbms_output.put_line('================== LIST ALL CUSTOMER AND PRODUCTS ==================');
    GET_CUST_STRING_VIASQLDEV(1);
    GET_CUST_STRING_VIASQLDEV(2);
    GET_CUST_STRING_VIASQLDEV(3);
    GET_CUST_STRING_VIASQLDEV(4);
    GET_PROD_STRING_VIASQLDEV(1001);
    GET_PROD_STRING_VIASQLDEV(1002);
    GET_PROD_STRING_VIASQLDEV(1003);
end;
